"""Add CASCADE delete to attempt

Revision ID: 1028ca58cbf8
Revises: c0d152340c3e
Create Date: 2024-05-25 18:38:25.255694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1028ca58cbf8'
down_revision: Union[str, None] = 'c0d152340c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submission_attempt_id_fkey', 'submission', type_='foreignkey')
    op.create_foreign_key(None, 'submission', 'attempt', ['attempt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.create_foreign_key('submission_attempt_id_fkey', 'submission', 'attempt', ['attempt_id'], ['id'])
    # ### end Alembic commands ###
