"""Add constraints to Participation

Revision ID: 1d042839842d
Revises: 46256ed78a9d
Create Date: 2024-03-22 22:26:28.946859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d042839842d'
down_revision: Union[str, None] = '46256ed78a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_participation', 'participation', ['user_id', 'course_id'])
    op.drop_constraint('participation_course_id_fkey', 'participation', type_='foreignkey')
    op.drop_constraint('participation_user_id_fkey', 'participation', type_='foreignkey')
    op.create_foreign_key(None, 'participation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'participation', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participation', type_='foreignkey')
    op.drop_constraint(None, 'participation', type_='foreignkey')
    op.create_foreign_key('participation_user_id_fkey', 'participation', 'user', ['user_id'], ['id'])
    op.create_foreign_key('participation_course_id_fkey', 'participation', 'course', ['course_id'], ['id'])
    op.drop_constraint('unique_participation', 'participation', type_='unique')
    # ### end Alembic commands ###
