"""Add image id to practice

Revision ID: 299ebb548a59
Revises: c528722d4084
Create Date: 2024-05-11 18:05:52.549034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299ebb548a59'
down_revision: Union[str, None] = 'c528722d4084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('image_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'image_id')
    # ### end Alembic commands ###
