"""Add is_request field in Participation

Revision ID: 46256ed78a9d
Revises: 54d0cb5de8d1
Create Date: 2024-03-15 21:38:22.018045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46256ed78a9d'
down_revision: Union[str, None] = '54d0cb5de8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participation', sa.Column('is_request', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participation', 'is_request')
    # ### end Alembic commands ###
