"""Add languages array to practice

Revision ID: 4f80b8382fcb
Revises: 54c6938cda60
Create Date: 2024-04-13 22:58:40.092881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f80b8382fcb'
down_revision: Union[str, None] = '54c6938cda60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('languages', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'languages')
    # ### end Alembic commands ###
