"""Add testcase relation

Revision ID: 54c6938cda60
Revises: fdc206eff897
Create Date: 2024-04-10 21:43:59.246972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54c6938cda60'
down_revision: Union[str, None] = 'fdc206eff897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input', sa.Uuid(), nullable=False),
    sa.Column('excepted', sa.Uuid(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('practice', 'test_outputs')
    op.drop_column('practice', 'test_inputs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('test_inputs', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('practice', sa.Column('test_outputs', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_table('testcase')
    # ### end Alembic commands ###
