"""Add practice table

Revision ID: 54d0cb5de8d1
Revises: b0d9717f7846
Create Date: 2024-03-15 20:52:26.891625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d0cb5de8d1'
down_revision: Union[str, None] = 'b0d9717f7846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('soft_deadline', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('practice_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice')
    # ### end Alembic commands ###
