"""Set Submission -> Attempt FK nullable

Revision ID: 91d00c97ec5a
Revises: efe8149a03c5
Create Date: 2024-05-31 23:10:40.532406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d00c97ec5a'
down_revision: Union[str, None] = 'efe8149a03c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'attempt_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'attempt_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
