"""Add runner params into practice

Revision ID: ade004f596ac
Revises: 26a1bfcc7ecd
Create Date: 2024-04-19 22:35:32.711137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade004f596ac'
down_revision: Union[str, None] = '26a1bfcc7ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('memory_limit', sa.Integer(), nullable=False))
    op.add_column('practice', sa.Column('time_limit', sa.Integer(), nullable=False))
    op.add_column('practice', sa.Column('max_threads', sa.Integer(), nullable=False))
    op.add_column('practice', sa.Column('command_line_args', sa.String(length=512), nullable=False))
    op.add_column('practice', sa.Column('network', sa.Boolean(), nullable=False))
    op.add_column('practice', sa.Column('allow_multi_file', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'allow_multi_file')
    op.drop_column('practice', 'network')
    op.drop_column('practice', 'command_line_args')
    op.drop_column('practice', 'max_threads')
    op.drop_column('practice', 'time_limit')
    op.drop_column('practice', 'memory_limit')
    # ### end Alembic commands ###
