"""Add image_id into course

Revision ID: be6925e77a6e
Revises: 299ebb548a59
Create Date: 2024-05-14 15:31:48.512449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6925e77a6e'
down_revision: Union[str, None] = '299ebb548a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('image_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'image_id')
    # ### end Alembic commands ###
