"""Add counters into attempt object

Revision ID: efe8149a03c5
Revises: 1028ca58cbf8
Create Date: 2024-05-31 22:53:15.944136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe8149a03c5'
down_revision: Union[str, None] = '1028ca58cbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('tests_needed', sa.Integer(), nullable=False))
    op.add_column('attempt', sa.Column('tests_completed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'tests_completed')
    op.drop_column('attempt', 'tests_needed')
    # ### end Alembic commands ###
