"""Merge task and practice

Revision ID: fdc206eff897
Revises: 1d042839842d
Create Date: 2024-04-06 18:35:16.891380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc206eff897'
down_revision: Union[str, None] = '1d042839842d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('description', sa.String(), nullable=False))
    op.add_column('practice', sa.Column('author_id', sa.Uuid(), nullable=False))
    op.add_column('practice', sa.Column('test_inputs', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('practice', sa.Column('test_outputs', sa.ARRAY(sa.String()), nullable=False))
    op.create_foreign_key(None, 'practice', 'user', ['author_id'], ['id'])
    op.drop_column('practice', 'practice_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('practice_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'practice', type_='foreignkey')
    op.drop_column('practice', 'test_outputs')
    op.drop_column('practice', 'test_inputs')
    op.drop_column('practice', 'author_id')
    op.drop_column('practice', 'description')
    # ### end Alembic commands ###
